services:


  backend:
    build:
      context: ./docker/php
    container_name: laravel_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - mongodb
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel
      DB_PASSWORD: secret

      MONGODB_URI: mongodb://mongodb:27017
      MONGODB_DATABASE: laravel_mongodb

    command: >
      sh -c "
      php artisan serve
      --host=0.0.0.0
      --port=8000
      "

 
  frontend:
    image: node:22-alpine
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
    command: >
      sh -c "
      npm install &&
      npm run dev -- --host 0.0.0.0
      "
    depends_on:
      - backend


  mysql:
    image: mysql:8.4
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  mongodb:
    image: mongo:8
    container_name: laravel_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: laravel_mongodb
    volumes:
      - mongodb_data:/data/db

volumes:
  mysql_data:
  mongodb_data: